global using NUnit.Framework;
global using FamBot;
global using FamBot.Data;
global using FamBot.Data.Services;
global using FamBotTests;
global using Ical.Net;
global using Serilog;
global using Serilog.Sinks.SystemConsole;
global using Serilog.Sinks.File;
